name: Test TEM_comms

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Dependencies
        run: python -m pip install pytest
      - name: Install
        run: pip install .
      - name: Test
        run: pytest
  pypi:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    permissions:
      id-token: write
    environment:
      name: testpypi
      url: https://test.pypi.org/p/pigeon-tem-comms/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Dependencies
        run: python3 -m pip install --user build
      - name: Build
        run: python3 -m build
      - name: Upload
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
  json:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Dependencies
        run: python3 -m pip install --user pigeon.js .
      - name: Build
        run: python3 -m pigeon_js TEM_comms
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release create "$GITHUB_REF_NAME" --repo "$GITHUB_REPOSITORY" --notes ""
      - name: Upload JSON
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release upload "$GITHUB_REF_NAME" TEM_comms.json --repo "$GITHUB_REPOSITORY"
      - name: Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "CameronDevine@users.noreply.github.com"
          git checkout origin/json && git pull origin json || git switch --orphan json
          git add TEM_comms.json
          git commit -m "Updating JSON message definitions."
          git push origin json
